name: phonebook
services:
  app:
    image: phonebook-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    depends_on:
    - backend

  backend:
    image: phonebook-backend
    build:
      context: ./backend
      dockerfile: Dockerfile 
    environment: 
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-phonebook
    depends_on:
      - app

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

volumes:
  mongo_data: